# Generated by Django 5.2.4 on 2025-08-07 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name or identifier', max_length=255)),
                ('code', models.CharField(help_text='Unique branch code within the company', max_length=20)),
                ('address', models.TextField(help_text='Branch physical address')),
                ('phone_number', models.CharField(blank=True, help_text='Branch contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Branch contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this branch is active')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Branch latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Branch longitude coordinate', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'companies_branch',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Company description or about information')),
                ('website', models.URLField(blank=True, help_text='Company website URL')),
                ('phone_number', models.CharField(blank=True, help_text='Company contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Company contact email', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Company headquarters address')),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company account is active')),
                ('subscription_plan', models.CharField(default='basic', help_text='Current subscription plan', max_length=50)),
                ('max_employees', models.PositiveIntegerField(default=50, help_text='Maximum number of employees allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=255)),
                ('code', models.CharField(help_text='Unique department code within the branch', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Department description or responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'companies_department',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, help_text="Employee's position/role in this department", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the employee joined this department')),
                ('left_at', models.DateTimeField(blank=True, help_text='When the employee left this department', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Membership',
                'verbose_name_plural': 'Department Memberships',
                'db_table': 'companies_departmentmembership',
            },
        ),
    ]
