# Generated by Django 5.2.4 on 2025-08-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Branch manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(help_text='Company owner/primary administrator', on_delete=django.db.models.deletion.PROTECT, related_name='owned_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(help_text='Company this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(help_text='Branch this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Department head/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='department',
            field=models.ForeignKey(help_text='Department the employee belongs to', on_delete=django.db.models.deletion.CASCADE, to='companies.department'),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='employee',
            field=models.ForeignKey(help_text='Employee in the department', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Employees in this department', related_name='departments', through='companies.DepartmentMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_branch_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'department'), name='unique_active_membership'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_department_code_per_branch'),
        ),
    ]
