# Generated by Django 5.2.4 on 2025-08-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='radius',
            field=models.PositiveIntegerField(default=100, help_text='Radius in meters for attendance check-in/out geofence'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_radius',
            field=models.PositiveIntegerField(default=100, help_text='Default radius in meters for attendance check-in/out geofence (applies to branches without specific radius)'),
        ),
    ]
