# Generated by Django 5.2.4 on 2025-08-15 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_details', models.JSONField(default=dict, help_text='Payment details like account numbers, transaction IDs, etc.')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admins')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('external_transaction_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment method name', max_length=100)),
                ('payment_type', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('CRYPTO', 'Cryptocurrency'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Instructions for this payment method')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True, help_text='Whether payments need manual approval')),
                ('config_fields', models.JSONField(blank=True, default=dict, help_text='Configuration for required fields (e.g., account number, routing number)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Professional Plan')", max_length=100)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('description', models.TextField(help_text='Plan description and features')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD (0.00 for free plan)', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('LIFETIME', 'Lifetime')], default='MONTHLY', max_length=20)),
                ('max_employees', models.PositiveIntegerField(default=10, help_text='Maximum number of employees (0 = unlimited)')),
                ('max_branches', models.PositiveIntegerField(default=1, help_text='Maximum number of branches (0 = unlimited)')),
                ('max_attendance_groups', models.PositiveIntegerField(default=5, help_text='Maximum attendance groups (0 = unlimited)')),
                ('has_advanced_reporting', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('has_data_export', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as recommended plan')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Payment'), ('TRIAL', 'Trial')], default='PENDING', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
            },
        ),
    ]
