# Generated by Django 5.2.4 on 2025-08-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_radius_fields'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_branch',
            field=models.ForeignKey(blank=True, help_text='Branch this HR manager is responsible for (HR_EMPLOYEE role only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_managers', to='companies.branch'),
        ),
    ]
