# Generated by Django 5.2.4 on 2025-08-07 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the attendance group (e.g., 'Main Office', 'Warehouse')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the attendance group')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate for check-in validation', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate for check-in validation', max_digits=9)),
                ('radius', models.PositiveIntegerField(default=100, help_text='Radius in meters within which employees can check in', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this attendance group is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Group',
                'verbose_name_plural': 'Attendance Groups',
                'db_table': 'attendance_attendancegroup',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the employee was assigned to this group')),
                ('removed_at', models.DateTimeField(blank=True, help_text='When the employee was removed from this group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Group Membership',
                'verbose_name_plural': 'Attendance Group Memberships',
                'db_table': 'attendance_attendancegroupmembership',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this attendance summary')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked', max_digits=5)),
                ('total_checkins', models.PositiveIntegerField(default=0, help_text='Total number of check-ins for the day')),
                ('is_present', models.BooleanField(default=False, help_text='Whether employee was present this day')),
                ('is_late', models.BooleanField(default=False, help_text='Whether employee was late')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_attendancesummary',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the check-in was made')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude where check-in was made', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude where check-in was made', max_digits=9)),
                ('type', models.CharField(choices=[('IN', 'Check-In'), ('OUT', 'Check-Out')], help_text='Type of check-in (IN/OUT)', max_length=3)),
                ('status', models.CharField(choices=[('ON_TIME', 'On Time'), ('LATE', 'Late'), ('EARLY', 'Early'), ('INVALID_LOCATION', 'Invalid Location'), ('INVALID_TIME', 'Invalid Time')], default='ON_TIME', help_text='Status of the check-in', max_length=20)),
                ('distance_from_location', models.FloatField(blank=True, help_text='Distance in meters from the attendance group location', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or comments')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which check-in was made', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check-In',
                'verbose_name_plural': 'Check-Ins',
                'db_table': 'attendance_checkin',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Period name (e.g., 'Morning Shift', 'Evening Shift')", max_length=100)),
                ('start_time', models.TimeField(help_text='Period start time')),
                ('end_time', models.TimeField(help_text='Period end time')),
                ('weekdays', models.CharField(help_text="Applicable weekdays (1=Monday, 7=Sunday). Format: '1,2,3,4,5'", max_length=15)),
                ('late_checkin_grace_minutes', models.PositiveIntegerField(default=15, help_text='Grace period in minutes for late check-in')),
                ('early_checkout_grace_minutes', models.PositiveIntegerField(default=15, help_text='Grace period in minutes for early check-out')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this period is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'attendance_period',
                'ordering': ['group', 'start_time'],
            },
        ),
    ]
