# Generated by Django 5.2.4 on 2025-08-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancegroup',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this attendance group is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_groups', to='companies.branch'),
        ),
        migrations.AddField(
            model_name='attendancegroup',
            name='company',
            field=models.ForeignKey(help_text='Company this attendance group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_groups', to='companies.company'),
        ),
        migrations.AddField(
            model_name='attendancegroupmembership',
            name='attendance_group',
            field=models.ForeignKey(help_text='Attendance group the employee is assigned to', on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancegroup'),
        ),
    ]
