# Generated by Django 5.2.4 on 2025-08-07 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancegroupmembership',
            name='employee',
            field=models.ForeignKey(help_text='Employee assigned to the attendance group', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancegroup',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='Employees assigned to this attendance group', related_name='attendance_groups', through='attendance.AttendanceGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='attendance_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='attendance.attendancegroup'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='attendance_group',
            field=models.ForeignKey(help_text='Attendance group for this check-in', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='attendance.attendancegroup'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='employee',
            field=models.ForeignKey(help_text='Employee who made this check-in', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='first_checkin',
            field=models.ForeignKey(blank=True, help_text='First check-in of the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_checkin_summaries', to='attendance.checkin'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='last_checkout',
            field=models.ForeignKey(blank=True, help_text='Last check-out of the day', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_checkout_summaries', to='attendance.checkin'),
        ),
        migrations.AddField(
            model_name='period',
            name='group',
            field=models.ForeignKey(help_text='Attendance group this period belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='attendance.attendancegroup'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Period this check-in is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='attendance.period'),
        ),
        migrations.AddConstraint(
            model_name='attendancegroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'attendance_group'), name='unique_active_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='attendancesummary',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_group', 'date'), name='unique_daily_attendance_summary'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['employee', '-timestamp'], name='attendance__employe_39bf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['attendance_group', '-timestamp'], name='attendance__attenda_831b66_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_590b89_idx'),
        ),
    ]
